#	#	#	#	#	#

include TokyoNightMoon.conf

# font
font_family		Maple Mono NF
bold_font		auto
italic_font		auto
bold_italic_font	auto
font_size		12

# window
hide_window_decotations		titlebar-only
window_padding_width		0
background_opacity		0.7
background_blur			32
background_color		#1e1e2e

# tab bar
tab_bar_edge		top
tab_bar_style		powerline

# shell
shell	zsh

# copy
clipboard_control write-primary write-clipboard no-append
copy_on_select yes
map ctrl+shift+p>f kitten hints --type path --program @
map ctrl+shift+p>l kitten hints --type line --program @
map ctrl+shift+p>w kitten hints --type word --program @
map ctrl+shift+p>h kitten hints --type hash --program @